//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TercumanSistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesaj
    {
        public int Id { get; set; }
        public string Mesaj { get; set; }
        public Nullable<int> Mesaj_Grup { get; set; }
        public Nullable<int> Gonderilen_id { get; set; }
    
        public virtual Tbl_Calisan Tbl_Calisan { get; set; }
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
    }
}
