//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TercumanSistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Metin
    {
        public int Id { get; set; }
        public Nullable<int> Musteri_id { get; set; }
        public string Metin { get; set; }
        public string Cev_metin { get; set; }
        public Nullable<int> Calisan_id { get; set; }
        public Nullable<int> Ucret { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<bool> Tam_onay { get; set; }
        public string kay_dil { get; set; }
        public string hed_dil { get; set; }
    
        public virtual Tbl_Calisan Tbl_Calisan { get; set; }
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
    }
}
